def middle_line():
    print('-'*20, end='')
    print('+', end='')
    print('-'*21, end='')
    print('+', end='')
    print('-'*33, end='')
    print('+', end='')
    print('-'*19, end='')
    print('+', end='')
    print('-'*14, end='')
    print('+', end='')
    print('-'*16)